version: "3.8"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
  cache:
    image: "redis:alpine"
    env_file:
      - .env
    ports:
      - "6379:6379"
    command: redis-server --requirepass "$REDIS_PASSWORD"
  database:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5432:5432"

